import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import hudson.model.User
import hudson.security.FullControlOnceLoggedInAuthorizationStrategy
import hudson.security.HudsonPrivateSecurityRealm
import hudson.security.csrf.DefaultCrumbIssuer
import jenkins.install.InstallState
import jenkins.model.Jenkins
import jenkins.model.JenkinsLocationConfiguration
import org.jenkinsci.plugins.workflow.job.WorkflowJob
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.StandardOpenOption
import java.nio.file.attribute.PosixFilePermissions
import java.security.MessageDigest
import java.security.SecureRandom
import javax.xml.parsers.DocumentBuilderFactory

// Mount only for a new, explicitly marked, empty Jenkins home. Never use on an existing controller.
def instance = Jenkins.get()
File home = instance.rootDir
File fresh = new File(home, '.flutter-cicd-central-fresh-home')
File complete = new File(home, '.flutter-cicd-central-setup-complete')
File stateFile = new File(home, '.flutter-cicd-central-bootstrap.json')
if (complete.exists() || !fresh.isFile()) {
    println('Central Flutter bootstrap: no fresh installation to initialize.')
    return
}
if (Files.isSymbolicLink(fresh.toPath()) || fresh.getText('UTF-8').trim() != 'flutter-cicd-central-v1') {
    throw new IllegalStateException('Unrecognized central fresh-home marker')
}
File answersFile = new File('/usr/share/jenkins/ref/central-answers.json')
File xmlFile = new File('/usr/share/jenkins/ref/central-job.xml')
if (!answersFile.isFile() || !xmlFile.isFile()) throw new IllegalStateException('Missing validated central answers/job XML')
def answers = new JsonSlurper().parse(answersFile, 'UTF-8')
if (!(answers instanceof Map) || answers.schema_version != 1 || answers.confirmed != true ||
        !(answers.project_id instanceof String) || !(answers.job_name instanceof String) ||
        !(answers.project_id ==~ /[A-Za-z][A-Za-z0-9_.-]{0,79}/) ||
        !(answers.job_name ==~ /[A-Za-z][A-Za-z0-9_.-]{0,79}/)) {
    throw new IllegalArgumentException('Use confirmed answers and job XML generated by automation/scripts/setup.py')
}
URI url = new URI(answers.jenkins.url)
if (!(url.scheme in ['http', 'https']) || !url.host || url.userInfo || url.query || url.fragment) {
    throw new IllegalArgumentException('Invalid Jenkins URL')
}
String ownership = "Managed by flutter-cicd-central; project_id=${answers.project_id}"
byte[] jobXml = Files.readAllBytes(xmlFile.toPath())
def factory = DocumentBuilderFactory.newInstance()
factory.setFeature('http://apache.org/xml/features/disallow-doctype-decl', true)
factory.setFeature('http://xml.org/sax/features/external-general-entities', false)
factory.setFeature('http://xml.org/sax/features/external-parameter-entities', false)
def document = factory.newDocumentBuilder().parse(new ByteArrayInputStream(jobXml))
def descriptions = document.documentElement.getElementsByTagName('description')
if (document.documentElement.nodeName != 'flow-definition' || descriptions.length == 0 ||
        descriptions.item(0).textContent != ownership) {
    throw new IllegalArgumentException('Central job XML ownership does not match answers')
}
String fingerprint = MessageDigest.getInstance('SHA-256').digest(
        (JsonOutput.toJson(answers) + '\n' + new String(jobXml, StandardCharsets.UTF_8))
        .getBytes(StandardCharsets.UTF_8)).encodeHex().toString()
boolean resuming = stateFile.isFile()
if (resuming) {
    def state = new JsonSlurper().parse(stateFile, 'UTF-8')
    if (state.version != 1 || state.config_hash != fingerprint) {
        throw new IllegalStateException('Interrupted bootstrap settings changed; inspect this home before resuming')
    }
} else if (!instance.getAllItems().isEmpty()) {
    throw new IllegalStateException('Refusing bootstrap: this Jenkins home already contains jobs')
}
def existingJob = instance.getItem(answers.job_name)
if (existingJob && (!(existingJob instanceof WorkflowJob) || existingJob.description != ownership)) {
    throw new IllegalStateException('Refusing to replace an unrelated job')
}
String adminName = 'flutter-cicd-admin'
def existingAdmin = User.getById(adminName, false)
if (existingAdmin && !resuming) throw new IllegalStateException('Refusing to replace an existing administrator')
if (!resuming) stateFile.setText(JsonOutput.toJson([version: 1, config_hash: fingerprint]), 'UTF-8')

File passwordFile = new File(home, 'secrets/flutter-cicd-central-admin-password')
Files.createDirectories(passwordFile.parentFile.toPath())
if (!passwordFile.exists()) {
    if (existingAdmin) throw new IllegalStateException('Administrator password file is missing')
    byte[] bytes = new byte[32]
    new SecureRandom().nextBytes(bytes)
    String generated = Base64.urlEncoder.withoutPadding().encodeToString(bytes)
    Files.createFile(passwordFile.toPath(), PosixFilePermissions.asFileAttribute(
            PosixFilePermissions.fromString('rw-------')))
    Files.write(passwordFile.toPath(), (generated + '\n').getBytes(StandardCharsets.UTF_8), StandardOpenOption.WRITE)
}
if (!passwordFile.isFile() || Files.isSymbolicLink(passwordFile.toPath())) {
    throw new IllegalStateException('Invalid administrator password file')
}
Files.setPosixFilePermissions(passwordFile.toPath(), PosixFilePermissions.fromString('rw-------'))
String password = passwordFile.getText('UTF-8').trim()
if (!(password ==~ /[A-Za-z0-9_-]{43}/)) throw new IllegalStateException('Invalid stored administrator password')
def realm = new HudsonPrivateSecurityRealm(false)
if (!existingAdmin) realm.createAccount(adminName, password)
instance.setSecurityRealm(realm)
def authorization = new FullControlOnceLoggedInAuthorizationStrategy()
authorization.setAllowAnonymousRead(false)
instance.setAuthorizationStrategy(authorization)
instance.setCrumbIssuer(new DefaultCrumbIssuer(false))
instance.setNumExecutors(1)
instance.save()
def location = JenkinsLocationConfiguration.get()
location.setUrl(answers.jenkins.url)
location.save()

if (!existingJob) instance.createProjectFromXML(answers.job_name, new ByteArrayInputStream(jobXml))
instance.setInstallState(InstallState.INITIAL_SETUP_COMPLETED)
instance.save()
complete.setText('flutter-cicd-central-v1\n', 'UTF-8')
Files.deleteIfExists(fresh.toPath())
println('Central Flutter bootstrap completed. Administrator password remains in the protected Jenkins home/secrets file. Run the first build after credentials and agents are ready.')
